### ISSUE TITLE
Revised version of the protocol - team Atreides

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#17]
Hi @open-sci/atreides,

As anticipated in [one of the previous lectures (practical part)](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to revise your protocol published on Protocols.io according to the reviews received by the members of the other team. Once your workflow revision is finalised, please publish it using the Protocols.io interface. 

In addition, you must also write and publish a response letter to the reviewers, explaining how you have addressed their comments or the justification for not addressing them (please remember that if the latter applies, then your justifications must be very robust). Once finalised, the response letter must be published in Zenodo, and it should explicitly link and mention (even in the metadata) the reviews received, the old version of the protocol and the revised one.

Then, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of the protocol revision and the response letter. The deadline to provide all this information is May 8th.

Do not hesitate to contact me in the Slack group with further questions.

**Comment by leonardozilli** [comment]
[revised version of the protocol](https://dx.doi.org/10.17504/protocols.io.3byl497wjgo5/v2)
[response letter](https://doi.org/10.5281/zenodo.11151960)
