### ISSUE TITLE
Submitting the software - team Harkonnen

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#19]
Hi @open-sci/harkonnen,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_3), once finalised, the [software you developed](https://github.com/open-sci/2023-2024-harkonnen-code) must be assigned with a DOI via Zenodo.

Once in Zenodo, close this issue by attaching the clickable DOI URL (https://doi.org/...) of the software to the comment. The version specified here must also be the one cited in the research article to write.

Do not hesitate to contact me in the Slack group with further questions.

**Comment by NicoleLiggeri** [comment]
[10.5281/zenodo.11307522](https://doi.org/10.5281/zenodo.11307522)

**Comment by NicoleLiggeri** [comment]
[10.5281/zenodo.11307522](https://doi.org/10.5281/zenodo.11307522)
