### ISSUE TITLE
Submitting the presentation - team Atreides

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#23]
Hi @open-sci/atreides,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1USObdYTaujrTikkRtqZlJ8zXh3C91dBezCxdTuskvi4/edit#slide=id.gd3972084b6_0_0), once finalised, the slides supporting your presentation must be uploaded on Zenodo by 09:00 on May 27th to get a DOI to refer to them.

Once in Zenodo, close this issue by attaching the slides' clickable DOI URL (https://doi.org/...) to the comment. Please remember to specify, in the title slide (the very first one), all the members of the group and the related roles each member has had in the context of the project, using the [CRediT – Contributor Roles Taxonomy](https://casrai.org/credit/), accompany each of the roles with a brief description of what has been done.

Do not hesitate to contact me in the Slack group with further questions.

**Comment by leonardozilli** [comment]
[https://doi.org/10.5281/zenodo.11344992](https://doi.org/10.5281/zenodo.11344992)
