### ISSUE TITLE
Updating the abstract - team Harkonnen

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#26]
Hi @open-sci/harkonnen,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to update the abstract you wrote and uploaded in the GitHub repository of the course with more precise and additional information derived from the study you have conducted so far (which also includes the information collected in the DMP and the protocol).

Once finalised, the abstract must be included in the research article. You have to prepare and submit it by the 25th of May, 23:59 Rome time. However, please update the abstract before writing the article and whenever you have either new or more precise information to share.

Do not hesitate to contact me in the Slack group with further questions.

**Comment by matteo-guenci** [comment]
[Updated version of the abstract.md](https://github.com/open-sci/2023-2024/blob/main/docs/Harkonnen/abstract.md)
