### ISSUE TITLE
Revision of material - team Atreides

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#29]
Dear @open-sci/atreides,

Please find here attached my comments on all your material. You have to address all of them and, once finalised, to close this issue with a comment containing your reply to each of the points I have highlighted. There is no specific deadline to complete this task, thus please take your time.

Please, be aware that some modifications in some documents may affect also modifications in other documents. As a final note, please remember to keep your notebooks up-to-date.

After closing this issue, please remember to update your material.md file by specifying the references to the new version of all your documents.

As usual, for further doubts, do not hesitate to contact me in the Slack channel or just comment on this issue here.

# General comments from the presentation

* In consideration of the order of the identifiers in your process, a lot of noise could be added from considering specific identifiers before others (e.g. ISBN before DOI and PMID). Please change the order of ID priority with DOI, PMID, ISBN, and then rerun the process to see if some differences arise.

* Related somehow to the previous question is also the absence, from the original dataset, of the types of entities in IRIS. Having and using that information allows you to make the wrong decisions (e.g. assigning an ISBN to a book chapter instead of a book). The new version of the new dataset has been recently released with this new information so as to track the types of entities as defined in IRIS. 

* It would be good also to understand how much of the entities in Meta aligns with the types in IRIS, indeed.

# DMP

### 1.1.1 What kind of research output are you describing?
- You talk about software here, but then you start talking about data afterwards

### 1.1.7 Why are you collecting/generating or re-using it?
- There are some layout problems in the PDF produced when the research questions are introduced.

### 2.1.1 Does the described output support any scientific publication?
- Well, I think it would support your article, right?

### 2.2.1 Does the described output use or support any published dataset?
- What does it mean that your software uses or supports GitHub?

### 3.1.1.1 What type(s) of persistent identifier(s) are used for the described dataset / output?
- Does it refer to the software? Which Data ids and Organization ids have you used? What is a Crossref identifier?

### 3.1.1.2 Will you provide metadata for the described dataset / output?
- DCAT is for dataset. Are you using it for software? How? I do not think it is an appropriate choice, but I'm open to change my mind.

### 3.1.1.7 How are searchable metadata provided?
- And how are these metadata available in LOD? What is the endpoint containing the metadata?

### 3.2.1.2 Is the selected repository a trusted source?
- Is GitHub following metadata standards? Which ones?
- Is GitHub support long-term preservation? I do not think so...

### 3.2.1.5 Does the repository(ies) assign datasets / outputs with persistent identifiers?
- I do not think GitHub does it...

### 3.2.2.2 How is the dataset / output shared?
- Should it be available also in Zenodo?

### 3.2.2.9 Please specify how the dataset / output will be accessed during and after the project ends
- What you specify here is not about the software but rather the data produced by running the software. These two datasets should be described in different "datasets" within the DMP, to have one dataset describing software, one dataset describing IRIS in Meta and another dataset describing IRIS in Index.

### 3.2.3.2 Under which license will metadata be provided?
- Software cannot be released in CC0, you have to use an appropriate open source license for it.

### 3.4.2 What reusability and / or reproducibility methods are followed?
- Here "analysis" what does it mean?

### 3.4.5 Is provenance well documented?
- How it is documented?

### 5.1.3 How will you preserve the described dataset / output in the long term?
- However, the code is preserved in another repository (that one about your code, indeed) and also in Zenodo.

### 1.1.6 What is its expected size?
- There is no unit of measure.

### 2.1.1 Does the described output support any scientific publication?
- Your paper?

### 2.3.1 Does the described output use or support any software?
- Is the software using the data, not vice versa.

### 3.1.1.2 Will you provide metadata for the described dataset / output?
- Where are the metadata described with this vocavbulary?

### 3.2.1.1 In which repository will the dataset / output be deposited?
- I think it is deposited in AMSActa, not in GitHub...

### 3.4.1 What internationally recognised licence will you use for your dataset / output?
- Why this license is different from the original one (CC0)?

### 5.1.3 How will you preserve the described dataset / output in the long term?
- Why to upload it on Figshare if it is already in AMSActa.

### 2.3.1 Does the described output use or support any software?
- See above.

### 3.1.1.2 Will you provide metadata for the described dataset / output?
- See above.

### 3.1.1.7 How are searchable metadata provided?
- Where are these LOD available?

### 3.2.1.3 Add certification(s)
- ISO27001? What's it?

# Protocol

- You have to state which version of Python you have used to run the software described in the workflow.

- The changes in the software highlighted above may result in changes to the "Expected result" here. My suggestion is not to use real values but just to highlight the type of data that is returned, specifying it would be fake data since it strongly depends on the input (e.g. a new version of Meta).

# Software

- It is important to mention here the version and machine you have used to run the software, so as to make it clear to a user what equipment he/she should have for using it.

# Data

- The data are shown, in the material.md, with a strange layout. Please fix it.

# Article

- Of course, you should extend the article according to the abovementioned modifications. More detailed comments as follows.

## Abstract
- The abstract should be your updated structured abstract...

## Introduction
- Where you introduce IRIS, you should explicitly tell the reader that the bibliographic information contained there are only those authored by UNIBO personnel. That is not clear from the text.
- Is it necessary to talk about OCIs in the context of your work? And in particular, in the introduction? If you feel like leaving it there, please provide an example of an OCI.

## Results
- If there is a bit too much schematic the text here - introduce the RQ and then answer it. I would suggest using a different narrative and then referring to the RQs every time some of the data you show answers to them.

**Comment by EricaAndreose** [comment]
# Answers to the comments from the presentation
### 1. Order of Identifiers in the Process
We reordered the priority of identifiers to prioritize DOI, followed by PMID, then ISBN. We re-runned the process.
Outcome: This adjustment reduces ambiguity and improves the reliability of entity matching and assignment. 
### 2. Absence of Entity Types in the Original Dataset
We integrated the updated version of the dataset containing the entity types from IRIS and changed the software to utilize this new information.
We incorporated this additional metadata into the decision-making process to ensure that identifiers are applied appropriately to their respective entity types.
We verified and corrected previous misassignments, if any, by mapping identifiers to entity types accurately.
### 3. Alignment Between Meta and IRIS Entity Types
We conducted a comparative analysis of entity types across both datasets.
We identified the extent of alignment and documented discrepancies or unique mappings.
This helped in harmonizing data, ensuring consistent categorization, and improving the robustness of data linkage.

![sankey_diagram@2x](https://github.com/user-attachments/assets/56b09664-a9d5-4b8b-9e31-bf444b749dc5)


# DMP
## Description: Open Science Project Software - Team Atreides - version 1
### 1.1.1 What kind of research output are you describing?
We update the description to reflect that the primary focus is the software, while subsequent references to data pertain to outputs or dependencies of the software.
### 1.1.7 Why are you collecting/generating or re-using it?
We solved the layout problems of the PDF version.
### 2.1.1 Does the described output support any scientific publication?
Yes, the software is intended to support the research article. We update this section to explicitly mention the article DOI.
### 2.2.1 Does the described output use or support any published dataset?
We changed the answer. It supports the IRIS data dump and we specify it’s DOI.
### 3.1.1.1 What type(s) of persistent identifier(s) are used for the described dataset / output?
We’re talking about the software and we added its zenodo DOI.
### 3.1.1.2 Will you provide metadata for the described dataset / output?
We choose to change the metadata standard from DCAT to DublinCore. We used it to create the “metadata.ttl” file that is available at the software zenodo DOI.
### 3.1.1.7 How are searchable metadata provided?
Metadata are not searchable.
### 3.2.1.2 Is the selected repository a trusted source?
We updated the answer adding the Zenodo repository.
### 3.2.1.5 Does the repository(ies) assign datasets / outputs with persistent identifiers?
We added Zenodo repository and it does.
### 3.2.2.2 How is the dataset / output shared?
We updated the answer adding the Zenodo and SoftwareHeritage repositories.
### 3.2.2.9 Please specify how the dataset / output will be accessed during and after the project ends
The software will be accessed via GitHub/Zenodo and the datasets will have their access mechanisms as described in the description section.
### 3.2.3.2 Under which license will metadata be provided?
We choose to change the license from CC0 to ISC License.
### 3.4.2 What reusability and / or reproducibility methods are followed?
We removed “analysis” and added the readme files.
### 3.4.5 Is provenance well documented?
We changed the answer as it’s not well documented.
### 5.1.3 How will you preserve the described dataset / output in the long term?
We added the GitHub and Zenodo repositories.

## Description: UNIBO IRIS bibliographic data dump - version 2
### 1.1.6 What is its expected size?
We added the correct size with unit of measure: 265 MB
### 2.1.1 Does the described output support any scientific publication?
We changed the answer to “yes” and added the paper metadata and DOI.
### 2.3.1 Does the described output use or support any software?
We change the answer to “no”.
### 3.1.1.2 Will you provide metadata for the described dataset / output?
We changed the answer to “no”.
### 3.2.1.1 In which repository will the dataset / output be deposited?
We added the correct doi to AMSActa repository.
### 3.4.1 What internationally recognised licence will you use for your dataset / output?
We changed the answer and added the correct CC0 License.
### 5.1.3 How will you preserve the described dataset / output in the long term?
We want to create an unique endpoint for the reproducibility of the experiment.
## Description: Iris in Meta - Version 1 and following ones
### 2.3.1 Does the described output use or support any software?
We changed the answer to “no”.
### 3.1.1.2 Will you provide metadata for the described dataset / output?
We changed the answer and explained that the metadata are stored in an XML/RDF file findable at the FigShare DOI:dx.doi.org/10.6084/m9.figshare.25879420
### 3.1.1.7 How are searchable metadata provided?
We changed the answer to “no” as they are not searchable.
### 3.2.1.3 Add certification(s)
We changed the answer to “no”.

# Protocol


- We added the python version both in the steps page and in the warning page of the protocol.


- The following line has been added to the 'guidelines' section of the protocol to explain this issue:
"The tables and values contained in the "expected result" snippets in this protocol are to be intended as reduced exemplars of the output expected from each step. The actual data may change depending on the version of the datasets used (e.g. a new version of Meta)."
# Software
- The README of the repository has been updated with clear indications for the python version required to run the software. Concerning the hardware specifications, they are mentioned in the protocol which is accessible from the repository of the software.
# Data
- We fixed the layout problem and updated the material.md file.
# Article
- We extended and changed the article taking care of adding the new implementations.
# Abstract
- The abstract was updated with the final structured abstract.


## Introduction


- We extended the article to include a passage that specifies that the bibliographic information contained regards only works authored by UNIBO personnel.


- We extended the article with a passage that explains what an OCI is, specifies their importance in our work, and provided an example.
## Results
- We changed the narrative approach removing the “question and answer” schema and trying to write a more discursive and observation-focused section centered on the results and what they led us to.

**Comment by essepuntato** [comment]
Dear @open-sci/atreides,

Thanks for the revision. You gained the maximum score for the project part (i.e. 17 points).
Have a nice day :-)
