### ISSUE TITLE
First version of DMP - team Harkonnen

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#5]
Hi @open-sci/harkonnen,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1NabMeG_OAxv6AoBLvHMTO0jMPXYSqznkvud7D0Jjg1k/edit#slide=id.gcbb39b4500_0_0), you have to create the first version of your Data Management Plan (DMP). The DMP should include at least the description of two datasets, i.e. one for the data you will gather and another for the software you will develop to analyse such data. Of course, if you need more than two datasets, please do not hesitate to add more.

The creation of the DMP must be done using an existing service, i.e. [OpenAIRE Argos](https://argos.openaire.eu). You should use your ORCID credentials to access it. In case you do not have an ORCID, please visit the [ORCID website](https://orcid.org/) and create a new account. In case you have some doubts about how to use the tool and what to fill in, please watch the recording of [today's lecture (27 March 2024)](https://github.com/open-sci/2023-2024) available in Panopto.

Once your first version of the DMP is finalised, please deposit it in Zenodo (by adding appropriate metadata) in at least a machine-readable format (e.g. JSON) and PDF. Then, close this issue by attaching the clickable DOI URL (https://doi.org/...) of the first version of the DMP to the comment.

The data stewards of the University of Bologna have created a valuable tool that can help you prepare for the DMP. It is a decision tree that guides a researcher in considering appropriate questions related to the managing of research data:

> Caldoni, G., Gualandi, B., & Marino, M. (2022). Research Data Management Decision Tree [Decision tree]. Alma Mater Studiorum - Università di Bologna. https://doi.org/10.5281/zenodo.7190005

Do not hesitate to contact me in the Slack group with further questions.

**Comment by ChiaraParravicini** [comment]
This is our DMP DOI URL: [https://doi.org/10.5281/zenodo.10950753](https://doi.org/10.5281/zenodo.10950753)
