### ISSUE TITLE
First version of the protocol - team Harkonnen

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#7]
Hi @open-sci/harkonnen,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1ODujBmeKCJmIBqZlzVBPioU_LPYaospnKs7CxQ0W_Ww/edit?usp=sharing), you have to create the first version of your workflow using [Protocols.io](https://protocols.io/).

The workflow should describe how you will address the research question related to your project. In particular, you
should focus on the steps to produce your output data (including explicit mentions of existing data and methods reused) and how these will be then analysed (e.g. by indicating which statistical tool or visualisation you will adopt) to answer your research question.

Once your first version of the workflow is finalised, please publish it using the Protocols.io interface. Then, close this issue by attaching the clickable DOI URL (https://doi.org/...) of the first version of the workflow in the comment.

Do not hesitate to contact me in the Slack group for further doubts.

**Comment by ChiaraParravicini** [comment]
This is the DOI URL of the first version of our workflow: [dx.doi.org/10.17504/protocols.io.261ge56qwg47/v1 ](dx.doi.org/10.17504/protocols.io.261ge56qwg47/v1)
