### ISSUE TITLE
Reviewing the Harkonnen DMP - team Atreides

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#9]
Hi @open-sci/atreides,

As anticipated in [one of the previous lectures](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), two of you have to review the [DMP developed by the team Harkonnen](https://github.com/open-sci/2023-2024/issues/5). The person selected for addressing this task must work independently to write a review and publish it on [Qeios](https://www.qeios.com/) to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once your review is published, close this issue by attaching the clickable DOI URLs (https://doi.org/...) of both reviews to the comment.

If you have any more questions, please don't hesitate to contact me in the Slack group.

**Comment by NicoleLiggeri** [comment]
https://doi.org/10.32388/U63N7W

**Comment by EricaAndreose** [comment]
https://doi.org/10.32388/6KC2WS

**Comment by leonardozilli** [comment]
My review of the Harkonnen's DMP: https://doi.org/10.32388/EWU6VH
